export class Country {
    name: String;
    code: String;
}

export const countries: Country[] = [{name: 'Aruba', code: 'ABW'},
{name: 'Afghanistan', code: 'AFG'},
{name: 'Angola', code: 'AGO'},
{name: 'Anguilla', code: 'AIA'},
{name: '\u00c5land Islands', code: 'ALA'},
{name: 'Albania', code: 'ALB'},
{name: 'Andorra', code: 'AND'},
{name: 'United Arab Emirates', code: 'ARE'},
{name: 'Argentina', code: 'ARG'},
{name: 'Armenia', code: 'ARM'},
{name: 'American Samoa', code: 'ASM'},
{name: 'Antarctica', code: 'ATA'},
{name: 'French Southern and Antarctic Lands', code: 'ATF'},
{name: 'Antigua and Barbuda', code: 'ATG'},
{name: 'Australia', code: 'AUS'},
{name: 'Austria', code: 'AUT'},
{name: 'Azerbaijan', code: 'AZE'},
{name: 'Burundi', code: 'BDI'},
{name: 'Belgium', code: 'BEL'},
{name: 'Benin', code: 'BEN'},
{name: 'Burkina Faso', code: 'BFA'},
{name: 'Bangladesh', code: 'BGD'},
{name: 'Bulgaria', code: 'BGR'},
{name: 'Bahrain', code: 'BHR'},
{name: 'Bahamas', code: 'BHS'},
{name: 'Bosnia and Herzegovina', code: 'BIH'},
{name: 'Saint Barth\u00e9lemy', code: 'BLM'},
{name: 'Belarus', code: 'BLR'},
{name: 'Belize', code: 'BLZ'},
{name: 'Bermuda', code: 'BMU'},
{name: 'Bolivia', code: 'BOL'},
{name: 'Brazil', code: 'BRA'},
{name: 'Barbados', code: 'BRB'},
{name: 'Brunei', code: 'BRN'},
{name: 'Bhutan', code: 'BTN'},
{name: 'Bouvet Island', code: 'BVT'},
{name: 'Botswana', code: 'BWA'},
{name: 'Central African Republic', code: 'CAF'},
{name: 'Canada', code: 'CAN'},
{name: 'Cocos (Keeling) Islands', code: 'CCK'},
{name: 'Switzerland', code: 'CHE'},
{name: 'Chile', code: 'CHL'},
{name: 'China', code: 'CHN'},
{name: 'Ivory Coast', code: 'CIV'},
{name: 'Cameroon', code: 'CMR'},
{name: 'DR Congo', code: 'COD'},
{name: 'Republic of the Congo', code: 'COG'},
{name: 'Cook Islands', code: 'COK'},
{name: 'Colombia', code: 'COL'},
{name: 'Comoros', code: 'COM'},
{name: 'Cape Verde', code: 'CPV'},
{name: 'Costa Rica', code: 'CRI'},
{name: 'Cuba', code: 'CUB'},
{name: 'Cura\u00e7ao', code: 'CUW'},
{name: 'Christmas Island', code: 'CXR'},
{name: 'Cayman Islands', code: 'CYM'},
{name: 'Cyprus', code: 'CYP'},
{name: 'Czechia', code: 'CZE'},
{name: 'Germany', code: 'DEU'},
{name: 'Djibouti', code: 'DJI'},
{name: 'Dominica', code: 'DMA'},
{name: 'Denmark', code: 'DNK'},
{name: 'Dominican Republic', code: 'DOM'},
{name: 'Algeria', code: 'DZA'},
{name: 'Ecuador', code: 'ECU'},
{name: 'Egypt', code: 'EGY'},
{name: 'Eritrea', code: 'ERI'},
{name: 'Western Sahara', code: 'ESH'},
{name: 'Spain', code: 'ESP'},
{name: 'Estonia', code: 'EST'},
{name: 'Ethiopia', code: 'ETH'},
{name: 'Finland', code: 'FIN'},
{name: 'Fiji', code: 'FJI'},
{name: 'Falkland Islands', code: 'FLK'},
{name: 'France', code: 'FRA'},
{name: 'Faroe Islands', code: 'FRO'},
{name: 'Micronesia', code: 'FSM'},
{name: 'Gabon', code: 'GAB'},
{name: 'United Kingdom', code: 'GBR'},
{name: 'Georgia', code: 'GEO'},
{name: 'Guernsey', code: 'GGY'},
{name: 'Ghana', code: 'GHA'},
{name: 'Gibraltar', code: 'GIB'},
{name: 'Guinea', code: 'GIN'},
{name: 'Guadeloupe', code: 'GLP'},
{name: 'Gambia', code: 'GMB'},
{name: 'Guinea-Bissau', code: 'GNB'},
{name: 'Equatorial Guinea', code: 'GNQ'},
{name: 'Greece', code: 'GRC'},
{name: 'Grenada', code: 'GRD'},
{name: 'Greenland', code: 'GRL'},
{name: 'Guatemala', code: 'GTM'},
{name: 'French Guiana', code: 'GUF'},
{name: 'Guam', code: 'GUM'},
{name: 'Guyana', code: 'GUY'},
{name: 'Hong Kong', code: 'HKG'},
{name: 'Heard Island and McDonald Islands', code: 'HMD'},
{name: 'Honduras', code: 'HND'},
{name: 'Croatia', code: 'HRV'},
{name: 'Haiti', code: 'HTI'},
{name: 'Hungary', code: 'HUN'},
{name: 'Indonesia', code: 'IDN'},
{name: 'Isle of Man', code: 'IMN'},
{name: 'India', code: 'IND'},
{name: 'British Indian Ocean Territory', code: 'IOT'},
{name: 'Ireland', code: 'IRL'},
{name: 'Iran', code: 'IRN'},
{name: 'Iraq', code: 'IRQ'},
{name: 'Iceland', code: 'ISL'},
{name: 'Israel', code: 'ISR'},
{name: 'Italy', code: 'ITA'},
{name: 'Jamaica', code: 'JAM'},
{name: 'Jersey', code: 'JEY'},
{name: 'Jordan', code: 'JOR'},
{name: 'Japan', code: 'JPN'},
{name: 'Kazakhstan', code: 'KAZ'},
{name: 'Kenya', code: 'KEN'},
{name: 'Kyrgyzstan', code: 'KGZ'},
{name: 'Cambodia', code: 'KHM'},
{name: 'Kiribati', code: 'KIR'},
{name: 'Saint Kitts and Nevis', code: 'KNA'},
{name: 'South Korea', code: 'KOR'},
{name: 'Kosovo', code: 'UNK'},
{name: 'Kuwait', code: 'KWT'},
{name: 'Laos', code: 'LAO'},
{name: 'Lebanon', code: 'LBN'},
{name: 'Liberia', code: 'LBR'},
{name: 'Libya', code: 'LBY'},
{name: 'Saint Lucia', code: 'LCA'},
{name: 'Liechtenstein', code: 'LIE'},
{name: 'Sri Lanka', code: 'LKA'},
{name: 'Lesotho', code: 'LSO'},
{name: 'Lithuania', code: 'LTU'},
{name: 'Luxembourg', code: 'LUX'},
{name: 'Latvia', code: 'LVA'},
{name: 'Macau', code: 'MAC'},
{name: 'Saint Martin', code: 'MAF'},
{name: 'Morocco', code: 'MAR'},
{name: 'Monaco', code: 'MCO'},
{name: 'Moldova', code: 'MDA'},
{name: 'Madagascar', code: 'MDG'},
{name: 'Maldives', code: 'MDV'},
{name: 'Mexico', code: 'MEX'},
{name: 'Marshall Islands', code: 'MHL'},
{name: 'Macedonia', code: 'MKD'},
{name: 'Mali', code: 'MLI'},
{name: 'Malta', code: 'MLT'},
{name: 'Myanmar', code: 'MMR'},
{name: 'Montenegro', code: 'MNE'},
{name: 'Mongolia', code: 'MNG'},
{name: 'Northern Mariana Islands', code: 'MNP'},
{name: 'Mozambique', code: 'MOZ'},
{name: 'Mauritania', code: 'MRT'},
{name: 'Montserrat', code: 'MSR'},
{name: 'Martinique', code: 'MTQ'},
{name: 'Mauritius', code: 'MUS'},
{name: 'Malawi', code: 'MWI'},
{name: 'Malaysia', code: 'MYS'},
{name: 'Mayotte', code: 'MYT'},
{name: 'Namibia', code: 'NAM'},
{name: 'New Caledonia', code: 'NCL'},
{name: 'Niger', code: 'NER'},
{name: 'Norfolk Island', code: 'NFK'},
{name: 'Nigeria', code: 'NGA'},
{name: 'Nicaragua', code: 'NIC'},
{name: 'Niue', code: 'NIU'},
{name: 'Netherlands', code: 'NLD'},
{name: 'Norway', code: 'NOR'},
{name: 'Nepal', code: 'NPL'},
{name: 'Nauru', code: 'NRU'},
{name: 'New Zealand', code: 'NZL'},
{name: 'Oman', code: 'OMN'},
{name: 'Pakistan', code: 'PAK'},
{name: 'Panama', code: 'PAN'},
{name: 'Pitcairn Islands', code: 'PCN'},
{name: 'Peru', code: 'PER'},
{name: 'Philippines', code: 'PHL'},
{name: 'Palau', code: 'PLW'},
{name: 'Papua New Guinea', code: 'PNG'},
{name: 'Poland', code: 'POL'},
{name: 'Puerto Rico', code: 'PRI'},
{name: 'North Korea', code: 'PRK'},
{name: 'Portugal', code: 'PRT'},
{name: 'Paraguay', code: 'PRY'},
{name: 'Palestine', code: 'PSE'},
{name: 'French Polynesia', code: 'PYF'},
{name: 'Qatar', code: 'QAT'},
{name: 'R\u00e9union', code: 'REU'},
{name: 'Romania', code: 'ROU'},
{name: 'Russia', code: 'RUS'},
{name: 'Rwanda', code: 'RWA'},
{name: 'Saudi Arabia', code: 'SAU'},
{name: 'Sudan', code: 'SDN'},
{name: 'Senegal', code: 'SEN'},
{name: 'Singapore', code: 'SGP'},
{name: 'South Georgia', code: 'SGS'},
{name: 'Svalbard and Jan Mayen', code: 'SJM'},
{name: 'Solomon Islands', code: 'SLB'},
{name: 'Sierra Leone', code: 'SLE'},
{name: 'El Salvador', code: 'SLV'},
{name: 'San Marino', code: 'SMR'},
{name: 'Somalia', code: 'SOM'},
{name: 'Saint Pierre and Miquelon', code: 'SPM'},
{name: 'Serbia', code: 'SRB'},
{name: 'South Sudan', code: 'SSD'},
{name: 'S\u00e3o Tom\u00e9 and Pr\u00edncipe', code: 'STP'},
{name: 'Suriname', code: 'SUR'},
{name: 'Slovakia', code: 'SVK'},
{name: 'Slovenia', code: 'SVN'},
{name: 'Sweden', code: 'SWE'},
{name: 'Swaziland', code: 'SWZ'},
{name: 'Sint Maarten', code: 'SXM'},
{name: 'Seychelles', code: 'SYC'},
{name: 'Syria', code: 'SYR'},
{name: 'Turks and Caicos Islands', code: 'TCA'},
{name: 'Chad', code: 'TCD'},
{name: 'Togo', code: 'TGO'},
{name: 'Thailand', code: 'THA'},
{name: 'Tajikistan', code: 'TJK'},
{name: 'Tokelau', code: 'TKL'},
{name: 'Turkmenistan', code: 'TKM'},
{name: 'Timor-Leste', code: 'TLS'},
{name: 'Tonga', code: 'TON'},
{name: 'Trinidad and Tobago', code: 'TTO'},
{name: 'Tunisia', code: 'TUN'},
{name: 'Turkey', code: 'TUR'},
{name: 'Tuvalu', code: 'TUV'},
{name: 'Taiwan', code: 'TWN'},
{name: 'Tanzania', code: 'TZA'},
{name: 'Uganda', code: 'UGA'},
{name: 'Ukraine', code: 'UKR'},
{name: 'United States Minor Outlying Islands', code: 'UMI'},
{name: 'Uruguay', code: 'URY'},
{name: 'United States', code: 'USA'},
{name: 'Uzbekistan', code: 'UZB'},
{name: 'Vatican City', code: 'VAT'},
{name: 'Saint Vincent and the Grenadines', code: 'VCT'},
{name: 'Venezuela', code: 'VEN'},
{name: 'British Virgin Islands', code: 'VGB'},
{name: 'United States Virgin Islands', code: 'VIR'},
{name: 'Vietnam', code: 'VNM'},
{name: 'Vanuatu', code: 'VUT'},
{name: 'Wallis and Futuna', code: 'WLF'},
{name: 'Samoa', code: 'WSM'},
{name: 'Yemen', code: 'YEM'},
{name: 'South Africa', code: 'ZAF'},
{name: 'Zambia', code: 'ZMB'},
{name: 'Zimbabwe', code: 'ZWE'}]
