const socialMap: Map < String, String >  = new Map < String, String > ();

    socialMap.set('DeviantArt', 'socicon-deviantart');
    socialMap.set('Facebook', 'socicon-facebook');
    socialMap.set('Github', 'socicon-github');
    socialMap.set('Google Plus', 'socicon-googleplus');
    socialMap.set('Instagram', 'socicon-instagram');
    socialMap.set('LinkedIn', 'socicon-linkedin');
    socialMap.set('Messenger', 'socicon-messenger');
    socialMap.set('Reddit', 'socicon-reddit');
    socialMap.set('Skype', 'socicon-skype');
    socialMap.set('Slack', 'socicon-slack');
    socialMap.set('Snapchat', 'socicon-snapchat');
    socialMap.set('Telegram', 'socicon-telegram');
    socialMap.set('Tumblr', 'socicon-tumblr');
    socialMap.set('Twitter', 'socicon-twitter');
    socialMap.set('WhatsApp', 'socicon-whatsapp');
    socialMap.set('Youtube', 'socicon-youtube');
    socialMap.set('Teamviewer', 'socicon-teamviewer');
    socialMap.set('Technorati', 'socicon-technorati');
    socialMap.set('Trip Advisor', 'socicon-tripadvisor');
    socialMap.set('Yandex', 'socicon-yandex');
    socialMap.set('Yelp', 'socicon-yelp');
    socialMap.set('VKontakte', 'socicon-vkontakte');
    socialMap.set('Warcraft', 'socicon-warcraft');
    socialMap.set('Wechat', 'socicon-wechat');
    socialMap.set('Weibo', 'socicon-weibo');
    socialMap.set('Wikipedia', 'socicon-wikipedia');
    socialMap.set('Windows', 'socicon-windows');
    socialMap.set('Wordpress', 'socicon-wordpress');
    socialMap.set('Twitch', 'socicon-twitch');
    socialMap.set('Uber', 'socicon-uber');
    socialMap.set('Zynga', 'socicon-zynga');
    socialMap.set('Xbox', 'socicon-xbox');
    socialMap.set('Xing', 'socicon-xing');
    socialMap.set('Yahoo', 'socicon-yahoo');
    socialMap.set('Yammer', 'socicon-yammer');
    socialMap.set('YouNow', 'socicon-younow');
    socialMap.set('Vimeo', 'socicon-vimeo');
    socialMap.set('Vine', 'socicon-vine');
    socialMap.set('TeamSpeak', 'socicon-teamspeak');
    socialMap.set('Soundcloud', 'socicon-soundcloud');
    socialMap.set('Spotify', 'socicon-spotify');
    socialMap.set('Stack Exchange', 'socicon-stackexchange');
    socialMap.set('Stack Overflow', 'socicon-stackoverflow');
    socialMap.set('Starcraft', 'socicon-starcraft');
    socialMap.set('OpenId', 'socicon-openid');
    socialMap.set('Opera', 'socicon-opera');
    socialMap.set('Outlook', 'socicon-outlook');
    socialMap.set('Overwatch', 'socicon-overwatch');
    socialMap.set('Patreon', 'socicon-patreon');
    socialMap.set('Paypal', 'socicon-paypal');
    socialMap.set('Periscope', 'socicon-periscope');
    socialMap.set('npm', 'socicon-npm');
    socialMap.set('MySpace', 'socicon-myspace');
    socialMap.set('Nintendo', 'socicon-nintendo');
    socialMap.set('Pinterest', 'socicon-pinterest');
    socialMap.set('Diablo', 'socicon-diablo');
    socialMap.set('Digg', 'socicon-digg');
    socialMap.set('Disqus', 'socicon-disqus');
    socialMap.set('Hackerrank', 'socicon-hackerrank');
    socialMap.set('Hearthstone', 'socicon-hearthstone');
    socialMap.set('IMDb', 'socicon-imdb');
    socialMap.set('ICQ', 'socicon-icq');
    socialMap.set('RSS', 'socicon-rss');
    socialMap.set('Slideshare', 'socicon-slideshare');
    socialMap.set('Steam', 'socicon-steam');
    socialMap.set('QQ', 'socicon-qq');
    socialMap.set('Quora', 'socicon-quora');
    socialMap.set('Lastfm', 'socicon-lastfm');
    socialMap.set('Livejournal', 'socicon-livejournal');
    socialMap.set('Lyft', 'socicon-lyft');
    socialMap.set('Goodreads', 'socicon-goodreads');
    socialMap.set('Google', 'socicon-google');
    socialMap.set('Google Scholar', 'socicon-googlescholar');
    socialMap.set('Google Groups', 'socicon-googlegroups');
    socialMap.set('Google Photos', 'socicon-googlephotos');
    socialMap.set('PlayStation', 'socicon-playstation');
    socialMap.set('Squarespace', 'socicon-squarespace');
    socialMap.set('Fiverr', 'socicon-fiverr');
    socialMap.set('Bitbucket', 'socicon-bitbucket');
    socialMap.set('8tracks', 'socicon-8tracks');
    socialMap.set('Airbnb', 'socicon-airbnb');
    socialMap.set('500px', 'socicon-500px');
    socialMap.set('Android', 'socicon-android');
    socialMap.set('Apple', 'socicon-apple');
    socialMap.set('Amazon', 'socicon-amazon');
    socialMap.set('Battle.net', 'socicon-battlenet');
    socialMap.set('Baidu', 'socicon-baidu');
    socialMap.set('Chrome', 'socicon-chrome');
    socialMap.set('Blizzard', 'socicon-blizzard');
    socialMap.set('Blogger', 'socicon-blogger');
    socialMap.set('Dailymotion', 'socicon-dailymotion');
    socialMap.set('Drupal', 'socicon-drupal');
    socialMap.set('eBay', 'socicon-ebay');
    socialMap.set('Etsy', 'socicon-etsy');
    socialMap.set('Firefox', 'socicon-firefox');
    socialMap.set('Flickr', 'socicon-flickr');
    socialMap.set('iTunes', 'socicon-itunes');
    socialMap.set('iStock', 'socicon-istock');
    socialMap.set('Craigslist', 'socicon-craigslist');
    socialMap.set('Google Maps', 'socicon-googlemaps');
    socialMap.set('Udemy', 'socicon-udemy');
    socialMap.set('Bing', 'socicon-bing');
    socialMap.set('Hacker News', 'socicon-hackernews');
    socialMap.set('Microsoft', 'socicon-microsoft');
    socialMap.set('CodePen', 'socicon-codepen');
    socialMap.set('Nat Geo', 'socicon-natgeo');
    socialMap.set('Tidal', 'socicon-tidal');
    socialMap.set('GitLab', 'socicon-gitlab');
    socialMap.set('Google Play', 'socicon-play');
    socialMap.set('Player.me', 'socicon-player');
    socialMap.set('MacOS', 'socicon-macos');
    socialMap.set('e-mail', 'socicon-mail');
    socialMap.set('mail.ru', 'socicon-mailru');
    socialMap.set('Viber', 'socicon-viber');
    socialMap.set('ViewBug', 'socicon-viewbug');
    socialMap.set('Wykop.pl', 'socicon-wykop');
    socialMap.set('Zapier', 'socicon-zapier');
    socialMap.set('Zerply', 'socicon-zerply');
    socialMap.set('Zomato', 'socicon-zomato');
    socialMap.set('Smashwords', 'socicon-smashwords');
    socialMap.set('Kobo', 'socicon-kobo');
    socialMap.set('BookBub', 'socicon-bookbub');
    socialMap.set('Instructables', 'socicon-instructables');
    socialMap.set('Origin', 'socicon-origin');
    socialMap.set('SmugMug', 'socicon-smugmug');
    socialMap.set('Songkick', 'socicon-songkick');
    socialMap.set('StayFriends.de', 'socicon-stayfriends');
    socialMap.set('Strava', 'socicon-strava');
    socialMap.set('StreamJar', 'socicon-streamjar');
    socialMap.set('StumbleUpon', 'socicon-stumbleupon');
    socialMap.set('Swarm', 'socicon-swarm');
    socialMap.set('TripIt', 'socicon-tripit');
    socialMap.set('Triple J', 'socicon-triplej');
    socialMap.set('Ventrilo', 'socicon-ventrilo');
    socialMap.set('Viadeo', 'socicon-viadeo');
    socialMap.set('del.icio.us', 'socicon-delicious');
    socialMap.set('Crunchbase', 'socicon-crunchbase');
    socialMap.set('Homefy', 'socicon-homefy');
    socialMap.set('Calendly', 'socicon-calendly');
    socialMap.set('Realtor.com', 'socicon-realtor');
    socialMap.set('Qobuz', 'socicon-qobuz');
    socialMap.set('Mastodon', 'socicon-mastodon');
    socialMap.set('Discord', 'socicon-discord');
    socialMap.set('Douban', 'socicon-douban');
    socialMap.set('Draugiem.lv', 'socicon-draugiem');
    socialMap.set('Dribbble', 'socicon-dribbble');
    socialMap.set('Ello.co', 'socicon-ello');
    socialMap.set('Endomodo', 'socicon-endomodo');
    socialMap.set('Envato', 'socicon-envato');
    socialMap.set('Nextdoor', 'socicon-nextdoor');
    socialMap.set('Unsplash', 'socicon-unsplash');
    socialMap.set('HomeAdvisor', 'socicon-homeadvisor');
    socialMap.set('Angie\'s List', 'socicon-angieslist');
    socialMap.set('LogMeIn', 'socicon-logmein');
    socialMap.set('GoToMeeting', 'socicon-gotomeeting');
    socialMap.set('AliExpress', 'socicon-aliexpress');
    socialMap.set('Guru', 'socicon-guru');
    socialMap.set('App Store', 'socicon-appstore');
    socialMap.set('FeedBurner', 'socicon-feedburner');
    socialMap.set('Filmweb', 'socicon-filmweb');
    socialMap.set('Flattr', 'socicon-flattr');
    socialMap.set('Formulr', 'socicon-formulr');
    socialMap.set('Forrst', 'socicon-forrst');
    socialMap.set('Foursquare', 'socicon-foursquare');
    socialMap.set('FriendFeed', 'socicon-friendfeed');
    socialMap.set('Grooveshark', 'socicon-grooveshark');
    socialMap.set('Smashcast', 'socicon-smashcast');
    socialMap.set('Horde', 'socicon-horde');
    socialMap.set('Houzz', 'socicon-houzz');
    socialMap.set('identi.ca', 'socicon-identica');
    socialMap.set('Issuu', 'socicon-issuu');
    socialMap.set('Keybase', 'socicon-keybase');
    socialMap.set('Lanyrd', 'socicon-lanyrd');
    socialMap.set('Zoom Video ', 'socicon-zoom');
    socialMap.set('Alibaba Group', 'socicon-alibaba');
    socialMap.set('wix', 'socicon-wix');
    socialMap.set('redfin', 'socicon-redfin');
    socialMap.set('googlecalendar', 'socicon-googlecalendar');
    socialMap.set('Shopify', 'socicon-shopify');
    socialMap.set('Freelancer', 'socicon-freelancer');
    socialMap.set('Seedrs', 'socicon-seedrs');
    socialMap.set('Doodle.com', 'socicon-doodle');
    socialMap.set('Bonanza', 'socicon-bonanza');
    socialMap.set('Toptal', 'socicon-toptal');
    socialMap.set('Gust', 'socicon-gust');
    socialMap.set('Trulia', 'socicon-trulia');
    socialMap.set('Loomly', 'socicon-loomly');
    socialMap.set('Upwork', 'socicon-upwork');
    socialMap.set('AngelList', 'socicon-angellist');
    socialMap.set('Appnet', 'socicon-appnet');
    socialMap.set('Bandcamp', 'socicon-bandcamp');
    socialMap.set('Mixer', 'socicon-mixer');
    socialMap.set('BeBee', 'socicon-bebee');
    socialMap.set('Bebo', 'socicon-bebo');
    socialMap.set('Behance', 'socicon-behance');
    socialMap.set('Buffer', 'socicon-buffer');
    socialMap.set('Coderwall', 'socicon-coderwall');
    socialMap.set('Curse', 'socicon-curse');
    socialMap.set('Deezer', 'socicon-deezer');
    socialMap.set('Fundable', 'socicon-fundable');
    socialMap.set('Zillow', 'socicon-zillow');
    socialMap.set('Niconico', 'socicon-niconico');
    socialMap.set('ToneDen', 'socicon-toneden');
    socialMap.set('Augment', 'socicon-augment');
    socialMap.set('Fyuse', 'socicon-fyuse');
    socialMap.set('Youtube Gaming', 'socicon-yt-gaming');
    socialMap.set('Sketchfab', 'socicon-sketchfab');
    socialMap.set('Mobcrush', 'socicon-mobcrush');
    socialMap.set('Pandora', 'socicon-pandora');
    socialMap.set('GameWisp', 'socicon-gamewisp');
    socialMap.set('Bloglovin\'', 'socicon-bloglovin');
    socialMap.set('TuneIn', 'socicon-tunein');
    socialMap.set('Game Jolt', 'socicon-gamejolt');
    socialMap.set('Trello', 'socicon-trello');
    socialMap.set('Spreadshirt', 'socicon-spreadshirt');
    socialMap.set('Alliance', 'socicon-alliance');
    socialMap.set('Meetup', 'socicon-meetup');
    socialMap.set('ShareThis', 'socicon-sharethis');
    socialMap.set('Mixcloud', 'socicon-mixcloud');
    socialMap.set('Mumble', 'socicon-mumble');
    socialMap.set('Newsvine', 'socicon-newsvine');
    socialMap.set('Odnoklassniki', 'socicon-odnoklassniki');
    socialMap.set('Pocket', 'socicon-pocket');
    socialMap.set('RaidCall', 'socicon-raidcall');
    socialMap.set('Ravelry', 'socicon-ravelry');
    socialMap.set('Renren', 'socicon-renren');
    socialMap.set('ResearchGate', 'socicon-researchgate');
    socialMap.set('Resident Advisor', 'socicon-residentadvisor');
    socialMap.set('ReverbNation', 'socicon-reverbnation');
    socialMap.set('amplement', 'socicon-amplement');
    socialMap.set('Booking.com', 'socicon-booking');
    socialMap.set('LINE', 'socicon-line');
    socialMap.set('Medium', 'socicon-medium');
    socialMap.set('Model Mayhem', 'socicon-modelmayhem');
    socialMap.set('Mozilla Persona', 'socicon-persona');
    socialMap.set('Livemaster', 'socicon-livemaster');
    socialMap.set('Storehouse', 'socicon-storehouse');
    socialMap.set('Ask', 'socicon-ask');
    socialMap.set('OpenAI Gym', 'socicon-openaigym');
    socialMap.set('Homes.com', 'socicon-homes');
    socialMap.set('hellocoton.fr', 'socicon-hellocoton');
    socialMap.set('CodeRED', 'socicon-codered');

export const socials = socialMap;

export const socialKeys = Array.from(socialMap.keys());
